apiVersion: v1
kind: ConfigMap
metadata:
    name: fluent-bit-config
    namespace: logging
    labels:
        k8s-app: fluent-bit
data:
    # Configuration files: server, input, filters and output
    # ======================================================
    fluent-bit.conf: |
        [SERVICE]
            Flush         1
            Log_Level     info
            Daemon        off
            Parsers_File  parsers.conf
            HTTP_Server   On
            HTTP_Listen   0.0.0.0
            HTTP_Port     2020

        @INCLUDE input-kubernetes.conf
        @INCLUDE filter-kubernetes.conf
        @INCLUDE output-kafka.conf

    input-kubernetes.conf: |
        [INPUT]
            Name              tail
            Tag               kube.*
            Path              /var/log/containers/*.log
            Parser            cri
            DB                /var/log/flb_kube.db
            Mem_Buf_Limit     5MB
            Skip_Long_Lines   On
            Refresh_Interval  10

    filter-kubernetes.conf: |
        [FILTER]
            Name                kubernetes
            Match               kube.*
            Kube_URL            https://kubernetes.default.svc:443
            Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
            Kube_Tag_Prefix     kube.var.log.containers.
            Merge_Log           Off
            Merge_Log_Trim      On
            Keep_Log            Off
            K8S-Logging.Parser  On
            K8S-Logging.Exclude Off
            Annotations         Off
            Labels              On

    output-kafka.conf: |
        [OUTPUT]
            Name        kafka
            Match       *
            Brokers     YOUR_AZURE_EVENT_HUB_NAMESPACE.servicebus.windows.net:9093
            Topics      YOUR_AZURE_EVENT_HUB
            Retry_Limit    2
            rdkafka.security.protocol SASL_SSL
            rdkafka.sasl.mechanism PLAIN
            rdkafka.sasl.username $ConnectionString
            rdkafka.sasl.password Endpoint=YOUR_AZURE_EVENT_HUB_NAMESPACE_PRIMARY_CONNECTION_STRING
            rdkafka.ssl.sa.location /usr/lib/ssl/certs/
            rdkafka.auto.offset.reset end
            rdkafka.request.timeout.ms 60000
            rdkafka.log.connection.close false
            rdkafka.queue.buffering.max.ms 1000
            rdkafka.queue.buffering.max.messages 300
            rdkafka.batch.num.messages 200
            rdkafka.compression.codec none
            rdkafka.request.required.acks 1
            rdkafka.queue.buffering.max.kbytes 10240

    parsers.conf: |
        [PARSER]
            Name        cri
            Format      regex
            Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
            Time_Key    time
            Time_Format %Y-%m-%dT%H:%M:%S.%L%z
